### ISSUE TITLE
Wrong color on editorOverviewRuler.background?

### ISSUE THREAD

**Issue by AlvaroParker** [AvetisDN/tokyo-dark-theme#1]
Looks like the wrong color is set on `editorOverviewRuler.background` in [tokyo-night.json](https://github.com/AvetisDN/tokyo-dark-theme/blob/main/themes/tokyo-night.json). Currently `editorOverviewRuler.background` is set to `#ffffff00` and the scroll bar looks like this [screenshot](https://imgur.com/a/7kc43QS).

When I set `editorOverviewRuler.background` to `#1a1b2600` the scrollbar looks "normal": [Screenshot](https://imgur.com/a/23NFKfp)

**Comment by AvetisDN** [comment]
Sorry for a long time no answer.
Thank you for your suggestion, fixed and published
